spring:
  datasource:
    url: jdbc:mysql://47.106.103.121:3306/sjroom-admin?serverTimezone=UTC&useTimezone=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&useSSL=false&allowMultiQueries=true
    username: root
    password: '!@#sh!@#'

logging:
  level:
    root: INFO