sjroom:
  security:
    # 不需要认证的请求
    no-authentication:
    - /doc.html
    - /webjars/**
    - /swagger-resources
    - /v2/**
    - /actuator
    - /actuator/**
    - /resources/**
    - /home
    - /**/favicon.ico
    - /error

spring:
  messages:
    basename: i18n/messages
    encoding: UTF-8
  resources:
    static-locations: classpath:/static/

logging:
  level:
    root: DEBUG

management:
  security:
    enabled: false